### ISSUE TITLE
Error while compiling on windows

### ISSUE THREAD

**Issue by nathan666** [schdub/dlcsign#1]
I am using latest libressl version.

C:\cygnus\cygwin-b20\H-i586-cygwin32\bin>g++ dlcsign.cpp -lssl -lcrypto -o dlcsign
In file included from ..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/bio.h:67,
                 from ..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/dsa.h:75,
                 from dlcsign.cpp:6:
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/crypto.h:496: warning: `deprecated' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/crypto.h:498: warning: `deprecated' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/crypto.h:500: warning: `deprecated' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/crypto.h:510: warning: `deprecated' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/crypto.h:512: warning: `deprecated' attribute directive ignored
In file included from ..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/dsa.h:75,
                 from dlcsign.cpp:6:
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/bio.h:622: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/bio.h:624: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/bio.h:626: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/bio.h:744: warning: `deprecated' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/bio.h:747: warning: `deprecated' attribute directive ignored
In file included from dlcsign.cpp:7:
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:101: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:104: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:110: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:113: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:134: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:137: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:140: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:143: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:182: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:185: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:188: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/sha.h:191: warning: `__bounded__' attribute directive ignored
In file included from ..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/x509.h:70,
                 from ..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/engine.h:97,
                 from dlcsign.cpp:9:
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/buffer.h:91: warning: `__bounded__' attribute directive ignored
..\\lib\\gcc-lib\\i586-cygwin32\\egcs-2.91.57\\..\\..\\..\\..\\..\\include\\g++\\openssl/buffer.h:93: warning: `__bounded__' attribute directive ignored
dlcsign.cpp: In function `class string fromHex(const class string &)':
dlcsign.cpp:53: parse error before `<'
dlcsign.cpp: In function `class string toHex(const unsigned char *, unsigned int, bool = false)':
dlcsign.cpp:64: no matching function for call to `string::push_back (char &)'
dlcsign.cpp:67: no matching function for call to `string::push_back (char &)'
dlcsign.cpp: In function `bool dlc_verify(const class string &, const class string &)':
dlcsign.cpp:80: no matching function for call to `vector<unsigned char,__default_alloc_template<false,0> >::data ()'
dlcsign.cpp: In function `bool dlc_sign(const class string &, class string &)':
dlcsign.cpp:103: no matching function for call to `vector<unsigned char,__default_alloc_template<false,0> >::data ()'

**Comment by schdub** [comment]
@nathan666, thanks for sharing.
Which version of GCC do you have installed (g++ -v)?
Source code didn't changed by you?

**Comment by nathan666** [comment]
Version is egcs-2.91.57
I have not changed the code.

**Comment by schdub** [comment]
https://stackoverflow.com/questions/34608904/sstream-no-such-file-or-directory
This version is really old, try to download last version of MinGW.
PS: I don't have experience with MinGW.

**Comment by nathan666** [comment]
Got it , thanks

**Comment by K1l14** [comment]
I'm having problems compiling on win10 gcc 6.3.0-1, I used the installer for mingw.

I have openssl Installed and I'm getting no such file or directory on the includes....
