### ISSUE TITLE
mingw64 & openssl-1.1.0 issues

### ISSUE THREAD

**Issue by K1l14** [schdub/dlcsign#2]
openssl-1.1.0i

gcc version 8.1.0 (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project)

C:\Users\owner\Desktop\mingw64\bin>g++ C:\Users\owner\Desktop\dlcsign-master\dlcsign.cpp -lssl -lcrypto -o dlcsign
C:\Users\owner\Desktop\dlcsign-master\dlcsign.cpp:6:10: fatal error: openssl/dsa.h: No such file or directory
#include <openssl/dsa.h>
^~~~~~~~~~~~~~~
compilation terminated.

any ideas on how to get this compiled?

no matter what i try i keep getting these errors with the includes...

**Comment by nathan666** [comment]
Try using ssl library from LibreSSL, works good for me.

**Comment by K1l14** [comment]
thanks for replying. ;0)

libressl-2.5.5-windows

after changing every include to point to where i have openssl, im getting this...

C:\Users\owner\Desktop\mingw64\bin>g++ C:/Users/owner/Desktop/dlcsign-master/dlcsign.cpp -lssl -lcrypto -o dlcsign
In file included from C:/openssl/include/openssl/engine.h:96,
                 from C:/Users/owner/Desktop/dlcsign-master/dlcsign.cpp:9:
C:/openssl/include/openssl/x509.h:120:2: warning: #warning overriding WinCrypt defines [-Wcpp]
 #warning overriding WinCrypt defines
  ^~~~~~~
C:/Users/owner/Desktop/dlcsign-master/dlcsign.cpp: In function 'bool dlc_sign(const string&, std::__cxx11::string&)':
C:/Users/owner/Desktop/dlcsign-master/dlcsign.cpp:120:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
C:/Users/owner/Desktop/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/Users/owner/Desktop/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
collect2.exe: error: ld returned 1 exit status

**Comment by nathan666** [comment]
No idea I am not a cpp developer.
Python would be better lol.
Just to make sure you know this script will not sign the dlc it will only verify it like the apk does.
I am more interested in how did they create a DSA Key with a custom length of 443 signs.

**Comment by K1l14** [comment]
me to, it's one of the two things im stuck on....

thanks for letting me know, i thought this would sign a custom dlc... ;0)

can i message you?

**Comment by schdub** [comment]
@K1l14, because you have incorrectly installed OpenSSL libs into your g++ compiler, you should:

> fatal error: openssl/dsa.h
use -I option to set path to include files of SSL

> cannot find -lssl
and use -L option to set path to .a files of SSL

    C:\Users\owner\Desktop\dlcsign-master>C:\Users\owner\Desktop\mingw64\bin\g++ -IC:/openssl/include -LC:/openssl/lib dlcsign.cpp -lssl -lcrypto -o dlcsign

**Comment by K1l14** [comment]
thanks for helping. ;0)
